
# html lang
language: zh-CN

# site info
description: 3wly 项目开发组自留地
keywords: M-finder,php,laravel,技术分享,个人博客,M-finder博客
# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# Miscelaneous
favicon: /images/favicon.ico
logo: /images/d-107.png

# stylesheets loaded in the <head>
stylesheets:
- /css/sense.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.4.1.min.js
- /js/sakura.js
- /js/sense.js

