
# html lang
language: zh-CN

# site info
description: 我是小妖怪，逍遥游自在，杀人不眨眼，吃人不放盐
keywords: d-107,m-finder,3wly,技术博客,技术分享
# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# SubNav
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# Miscelaneous
favicon: /images/favicon.ico
logo: /images/d-107.png

# friend links
friends:
  AprilBlank: http://www.aprilblank.com
  大白: http://blog.csdn.net/qq_27948659
  Sgclzqq: http://www.sgclzqq.com/
  Wait: https://93xiaosi.github.io/
  Wang WeiQiang: https://thekingstyle.github.io/

# stylesheets loaded in the <head>
stylesheets:
- /css/sense.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-3.4.1.min.js
- /js/sakura.js
- /js/sense.js

